### ISSUE TITLE
Can't spawn vehicle

### ISSUE THREAD

**Issue by nabi11** [esx-framework/esx_jobs#59]
on every jobs with the jobs outfits i can't spawn any vehicle on any jobs (ex: fisherman is not able to spawn boat.)

**Comment by shyricaus** [comment]
The same thing is happening to me, and when I try to get the vehicle ta giving this error.

![image](https://user-images.githubusercontent.com/28937245/49060715-d6edf280-f1f5-11e8-9bb0-3f1b0cd69940.png)

**Comment by shyricaus** [comment]
![image](https://user-images.githubusercontent.com/28937245/49331603-0a7aa500-f587-11e8-8634-9d15da18b174.png)

**Comment by shyricaus** [comment]
![image](https://user-images.githubusercontent.com/28937245/49331610-1d8d7500-f587-11e8-98b9-a4491fbe9d39.png)

**Comment by Rynatyy** [comment]
Same here

**Comment by Ffrankys** [comment]
Still having a problem?

**Comment by ColeT3tr3x** [comment]
Any fix? Currently can't spawn boat/vehicles, and the outfits aren't set so if anyone has the outfits i'd appreciate that as well.

**Comment by OutdoorTorrey** [comment]
Having the same issue

**Comment by aleexnl** [comment]
HIf you enable the caution in the spawn oints maybe u can, that worked for me 👯

**Comment by DevDokus** [comment]
I got a quick fix for you guys, look at this. 
![image](https://user-images.githubusercontent.com/49053928/81028723-ecebf200-8e82-11ea-89d9-23fa1427ce5a.png)
In the server/main.lue - line 118 you see a line that says 
`if cautionAmount <= Config.MaxCaution and cautionAmount > 0 then`
if cautionAmount is less then or equal to Config.MaxCaution and maxCaution is bigger then 0. 

The weird thing here is that when i print those values in my console, cautionAmount is always 0. Meaning that the 2nd statement cautionAmount is greater then 0 is always false because there is no check for it being equal like the first statement.  By simply adding a = after > you check also for equal. Then you get. cautionAmount is bigger then or equal to 0 instead of bigger then 0. 
Because if the cautionAmount returns a 0 upon requesting the boat, the script will not continue because the 2nd statement should return a true (thus bigger then 0) to continue the script.

If you dont want to do it yourself >> https://pastebin.com/8ST6kgSU

NOTE: I did not fixed yet selling the boat. Not sure if it does not sell for you guys also ?
I notice in the console that cautionType (what can be take or gibe_back) is always "take" even if you drive back with the boat over the circle. thus is never activates the selling part. Lacking time on it right now but ill update this post later on when i got it to work.

**Comment by HumanTree92** [comment]
I have ended up removing the boat completely for Fisherman. Instead i have it setup where players drive up to paleto bay to fish of the dock. The time to catch fix is raised as well.

**Comment by josh-tf** [comment]
Hey guys, sorry bit late to the party

I was able to get this working using @DevDokus's fix and another one

Do his fix first and then in **/client/main.lua** change:

`		if vehicle.HasCaution then
			vehicleInCaseofDrop = spawnedVehicle
			vehicleObjInCaseofDrop = vehicle
			vehicleMaxHealth = GetVehicleEngineHealth(spawnedVehicle)
		end
`

to

`
			vehicleInCaseofDrop = spawnedVehicle
			vehicleObjInCaseofDrop = vehicle
			vehicleMaxHealth = GetVehicleEngineHealth(spawnedVehicle)
`

Probably not the best way to sort this one out but its solved for me so not going to look more in to it, shouldn't be any issues with setting those values even if there is no bond/deposit amount

**Comment by SrLicht** [comment]
![image](https://user-images.githubusercontent.com/36207738/84134885-9d6b8980-aa1f-11ea-857b-d532540dcd98.png)
Still not working for me :/

**Comment by SrLicht** [comment]
![image](https://user-images.githubusercontent.com/36207738/84134996-c68c1a00-aa1f-11ea-9826-6b12ecd7f103.png)
![image](https://user-images.githubusercontent.com/36207738/84135036-d60b6300-aa1f-11ea-9898-7fad92107419.png)

**Comment by SrLicht** [comment]
Forget it, manage to fix it by downloading this fork
https://github.com/KarmaUnderground/esx_jobs

**Comment by BrakingESX247** [comment]
Very outdated.
